coverage:
  status:
    project:
      default:
        target: 68%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
    patch:
      default:
        target: 62%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
codecov:
  require_ci_to_pass: true